-- =============================================================================
-- Hyprland Lua Configuration
-- Sonokai Dark Theme | Vim-style Keybindings | Auto Monitor Detection
-- Requires Hyprland >= 0.55 (Lua config support)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Sonokai Default Style Colors (rgba format: rrggbbaa)
-- -----------------------------------------------------------------------------
local colors = {
  black     = "rgba(181819ff)",
  bg_dim    = "rgba(222327ff)",
  bg0       = "rgba(2c2e34ff)",
  bg1       = "rgba(33353fff)",
  bg2       = "rgba(363944ff)",
  bg3       = "rgba(3b3e48ff)",
  bg4       = "rgba(414550ff)",
  bg_red    = "rgba(55393dff)",
  bg_yellow = "rgba(4e432fff)",
  bg_green  = "rgba(394634ff)",
  bg_blue   = "rgba(354157ff)",
  bg_purple = "rgba(434055ff)",
  fg        = "rgba(e2e2e3ff)",
  red       = "rgba(fc5d7cff)",
  orange    = "rgba(f39660ff)",
  yellow    = "rgba(e7c664ff)",
  green     = "rgba(9ed072ff)",
  blue      = "rgba(76cce0ff)",
  purple    = "rgba(b39df3ff)",
  grey      = "rgba(7f8490ff)",
  grey_dim  = "rgba(595f6faa)",
}

-- -----------------------------------------------------------------------------
-- Device detection: laptop has a battery; desktop does not
-- -----------------------------------------------------------------------------
local function is_laptop()
  local handle = io.popen("ls /sys/class/power_supply/ 2>/dev/null | grep -i bat")
  if handle then
    local result = handle:read("*a")
    handle:close()
    return result ~= ""
  end
  return false
end

local laptop     = is_laptop()

-- -----------------------------------------------------------------------------
-- Programs
-- -----------------------------------------------------------------------------
local terminal   = "wezterm"
local menu       = "wofi --show drun"

-- Volume cap: 1.0 = 100%, 1.5 = 150%. Set to nil to allow unlimited.
local volume_cap = 1.5

-- -----------------------------------------------------------------------------
-- ENVIRONMENT VARIABLES
-- -----------------------------------------------------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
-- Required portal behavior depends on these three
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
-- Qt: force Wayland so Qt apps don't fall back to blurry XWayland
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
-- GTK / Electron
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("GDK_DPI_SCALE", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("NIXOS_OZONE_WL", "1")

-- -----------------------------------------------------------------------------
-- MONITORS
-- Auto-detect every monitor at its highest refresh rate,
-- secondary monitors use their own workspaces (extended desktop).
-- -----------------------------------------------------------------------------
hl.monitor({
  output   = "",
  mode     = "highrr",
  position = "auto",
  scale    = "auto",
})

-- -----------------------------------------------------------------------------
-- AUTOSTART
-- Copied-by-example warning: this is a hand-written config, no autogenerated
-- flag is set, so no yellow warning bar is shown.
-- -----------------------------------------------------------------------------
hl.on("hyprland.start", function()
  -- Status bar (login-start, keep it running)
  hl.exec_cmd("pgrep -x waybar || waybar &")
  -- Notification daemon (required by waybar notification modules)
  hl.exec_cmd("pgrep -x mako || mako &")
  -- Polkit authentication agent (GUI privilege prompts)
  hl.exec_cmd("pgrep -x hyprpolkitagent || hyprpolkitagent &")
  -- XDG Desktop Portal (screenshot/screen-share is Hyprland's backend,
  -- file chooser still needs the gtk portal to coexist)
  hl.exec_cmd("pgrep -x xdg-desktop-portal-hyprland || /usr/lib/xdg-desktop-portal-hyprland &")
  -- Idle daemon (auto suspend/lock)
  hl.exec_cmd("pgrep -x hypridle || hypridle &")
  -- Wallpaper
  hl.exec_cmd("pgrep -x hyprpaper || hyprpaper &")
  -- Network manager applet
  hl.exec_cmd("pgrep -x nm-applet || nm-applet &")
end)

-- -----------------------------------------------------------------------------
-- GENERAL
-- -----------------------------------------------------------------------------
hl.config({
  general = {
    gaps_in          = 3,
    gaps_out         = 6,
    border_size      = 2,
    col              = {
      active_border   = { colors = { colors.blue, colors.purple }, angle = 45 },
      inactive_border = colors.grey_dim,
    },
    resize_on_border = true,
    allow_tearing    = false,
    layout           = "dwindle",
  },
})

-- -----------------------------------------------------------------------------
-- DECORATION
-- -----------------------------------------------------------------------------
hl.config({
  decoration = {
    rounding         = 6,
    rounding_power   = 2,
    active_opacity   = 1.0,
    inactive_opacity = 0.95,

    shadow           = {
      enabled      = true,
      range        = 4,
      render_power = 3,
      color        = 0x66000000, -- AARRGGBB
    },

    blur             = {
      enabled  = true,
      size     = 3,
      passes   = 1,
      vibrancy = 0.1696,
    },
  },
})

-- -----------------------------------------------------------------------------
-- ANIMATIONS (minimal, performance-first)
-- -----------------------------------------------------------------------------
hl.config({
  animations = {
    enabled = false,
  },
})

-- -----------------------------------------------------------------------------
-- INPUT
-- -----------------------------------------------------------------------------
hl.config({
  input = {
    kb_layout     = "us",
    follow_mouse  = 1,
    sensitivity   = 0,
    accel_profile = "adaptive",
    touchpad      = {
      natural_scroll = true,
    },
  },
})

-- -----------------------------------------------------------------------------
-- LAYOUTS
-- -----------------------------------------------------------------------------
hl.config({
  dwindle = {
    preserve_split = true,
    smart_split    = false,
    smart_resizing = true,
  },
  master = {
    new_status = "master",
  },
})

-- -----------------------------------------------------------------------------
-- MISC
-- -----------------------------------------------------------------------------
hl.config({
  misc = {
    force_default_wallpaper     = 0,
    disable_hyprland_logo       = true,
    disable_splash_rendering    = true,
    mouse_move_enables_dpms     = true,
    key_press_enables_dpms      = true,
    save_window_size            = true,
    allow_parent_footer_closing = false,
  },
})

-- -----------------------------------------------------------------------------
-- GESTURES (touchpad laptop only)
-- -----------------------------------------------------------------------------
if laptop then
  hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
  })
end

-- -----------------------------------------------------------------------------
-- KEYBINDINGS
-- -----------------------------------------------------------------------------
local mainMod = "SUPER"

-- Window focus (Vim-style)
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))

-- Move windows (Super+Ctrl+HJKL)
hl.bind(mainMod .. " + CTRL + h", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + CTRL + j", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + CTRL + k", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + CTRL + l", hl.dsp.window.move({ direction = "right" }))

-- Resize windows (Super+Shift+HJKL)
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.resize({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.resize({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.resize({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.resize({ direction = "right" }))

-- Arrow key alternatives for focus
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Arrow key alternatives for move
hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.move({ direction = "down" }))

-- Arrow key alternatives for resize
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.resize({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.resize({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.resize({ direction = "down" }))

-- Workspace switch (Super + 1-9) and move-to-workspace (Super+Shift+1-9)
for i = 1, 9 do
  local key = i % 10
  hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
  hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Special (scratchpad) workspace
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Applications
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + d", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + c", hl.dsp.window.close())
hl.bind(mainMod .. " + v", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + p", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + t", hl.dsp.layout("togglesplit"))

-- Fullscreen
hl.bind(mainMod .. " + f", hl.dsp.window.fullscreen())

-- Pin window
hl.bind(mainMod .. " + CTRL + p", hl.dsp.window.pin())

-- Monitor navigation
hl.bind(mainMod .. " + bracketleft", hl.dsp.focus({ monitor = "e-1" }))
hl.bind(mainMod .. " + bracketright", hl.dsp.focus({ monitor = "e+1" }))
hl.bind(mainMod .. " + SHIFT + bracketleft", hl.dsp.window.move({ monitor = "e-1" }))
hl.bind(mainMod .. " + SHIFT + bracketright", hl.dsp.window.move({ monitor = "e+1" }))

-- Mouse bindings
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Exit (minimal philosophy: no wlogout, one hotkey)
hl.bind(mainMod .. " + SHIFT + e", hl.dsp.exit())

-- Lock screen (hyprlock)
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("pidof hyprlock || hyprlock"))

-- Media keys (volume, no hard-coded 100% cap)
local vol_cap_arg = volume_cap and ("-l " .. volume_cap) or ""
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume " .. vol_cap_arg .. " @DEFAULT_AUDIO_SINK@ 5%+"),
  { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
  { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
  { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
  { locked = true, repeating = true })

-- Brightness (laptop only)
if laptop then
  hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
  hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
end

-- Screenshots (require grim + slurp + wl-clipboard)
hl.bind(",", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"), { locked = true })
hl.bind("SHIFT + ,", hl.dsp.exec_cmd("grim - | wl-copy"), { locked = true })

-- -----------------------------------------------------------------------------
-- WINDOW RULES
-- -----------------------------------------------------------------------------

-- Suppress maximize events from apps (avoids layout bugs)
hl.window_rule({
  name           = "suppress-maximize",
  match          = { class = ".*" },
  suppress_event = "maximize",
})

-- Fix XWayland drag regressions
hl.window_rule({
  name     = "fix-xwayland-drags",
  match    = {
    class      = "^$",
    title      = "^$",
    xwayland   = true,
    float      = true,
    fullscreen = false,
    pin        = false,
  },
  no_focus = true,
})

-- Float rules for small tools (everything else stays fully tiled)
local float_tools = {
  "Calculator",
  "gnome-calendar",
  "pavucontrol",
  "nm-connection-editor",
  "blueman-manager",
  "file-roller",
  "ark",
  "gnome-font-viewer",
  "arandr",
  "veracrypt",
  "fileprogress",
  "gcr-prompter",
  "gnome-shell",
  "kleo",
  "org.gnome.Settings",
  "org.gnome.tweaks",
  "pwvucontrol",
  "qalculate-gtk",
  "qt5ct",
  "qt6ct",
  "slack",
  "solaar",
  "thunar",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
  "zenity",
}

for _, class in ipairs(float_tools) do
  hl.window_rule({
    name   = "float-" .. class,
    match  = { class = class },
    float  = true,
    center = true,
  })
end

-- Float + pin for picture-in-picture
hl.window_rule({
  name   = "float-picture-in-picture",
  match  = { title = "Picture-in-Picture" },
  float  = true,
  pin    = true,
  on_top = true,
})

-- Float + center for file progress dialogs
hl.window_rule({
  name   = "float-file-progress",
  match  = { title = "File Operation Progress" },
  float  = true,
  center = true,
})

-- Terminal opacity
hl.window_rule({
  name             = "opacity-terminal",
  match            = { class = "^(Alacritty|kitty|wezterm|foot|ghostty)$" },
  active_opacity   = 1.0,
  inactive_opacity = 0.95,
})

-- Blur behind waybar
hl.layer_rule({
  name  = "waybar",
  match = { namespace = "waybar" },
  blur  = true,
})

-- -----------------------------------------------------------------------------
-- END OF CONFIG
-- -----------------------------------------------------------------------------

